# Site settings
title: David
description: Chatbot for storing tasks
url: "https://incogdino.github.io/ip/" # Your GitHub Pages URL
github_username: your-username

# Build settings
markdown: kramdown
kramdown:
  input: GFM # This enables GitHub Flavored Markdown (GFM)
